# Generated by Django 4.1.4 on 2022-12-28 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inspeccionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInspeccion', models.DateField(default=datetime.datetime(2022, 12, 28, 17, 6, 16, 580661))),
                ('informeUrl', models.CharField(default='', max_length=512)),
                ('videoUrl', models.CharField(default='', max_length=512)),
                ('resultadoUrl', models.CharField(default='', max_length=512)),
                ('nombreUnidadMinera', models.CharField(default='', max_length=128)),
                ('nombreOperacion', models.CharField(default='', max_length=128)),
                ('detalleInspeccion', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
