# Generated by Django 4.1.4 on 2022-12-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumi', '0002_alter_inspeccioninfo_fechainspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccioninfo',
            name='estadoInspeccion',
            field=models.CharField(default='', max_length=128),
        ),
    ]
